version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  backend:
    build: .
    ports:
      - 8000:8000
    command: sh entrypoints.sh
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
